name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: unbuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World!"
      - name: Print Goodbye
        run: echo "GoodBye"
      
